### ISSUE TITLE
Status of this library?

### ISSUE THREAD

**Issue by tomchadwin** [calvinmetcalf/topojson.py#21]
I'm looking for ways to add d3 export to qgis2web:

https://github.com/tomchadwin/qgis2web/issues/171

This library could be an essential part, to generate the topoJSON from QGIS's exported geoJson. Is this library stable and functional?

**Comment by calvinmetcalf** [comment]
so pretty much as soon as I finished this library I switched jobs to one where I never touched python really ever anymore, so my maintenance of this is somewhat limited but @scw has helped maintain it and it should work, it just is somewhat orphaned.

**Comment by scw** [comment]
The library has its warts, but it does work and if you have issues, I'm happy to poke around to help fix them.

**Comment by tomchadwin** [comment]
Brilliant. Not about to work on this yet, but it might come up in the next few months.
