### ISSUE TITLE
abandoned? 

### ISSUE THREAD

**Issue by Casyfill** [calvinmetcalf/topojson.py#25]
Sorry to bother, but noticed there were no PR merged in a long period of time. Is it on purpose or this repo is, generally, abandoned? I am asking as I use it rather heavily for my data transformations,

also trying to convince maintainers to include it as optionald dependency for geojson, [here](https://github.com/geopandas/geopandas/pull/645).  Do you mind if I'll try to make it pip-installable?

Best,
Philipp

**Comment by calvinmetcalf** [comment]
pretty much as soon as I created this I got a new job where I no longer did any python stuff so I wouldn't say abandoned as much as up for adoption.

**Comment by calvinmetcalf** [comment]
pretty much as soon as I created this I got a new job where I no longer did any python stuff so I wouldn't say abandoned as much as up for adoption.

**Comment by calvinmetcalf** [comment]
@scw is already a collaborator and I've added you as well

**Comment by calvinmetcalf** [comment]
I actually havn't left the GIS space, I just left the python space, I
maintain proj4js

**Comment by Casyfill** [comment]
Ah, ic,
awesome!



‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>
